# Generated by Django 2.1.1 on 2018-11-03 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181103_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 17, 31, 58, 268625)),
        ),
    ]
