# Generated by Django 2.1.1 on 2018-11-06 15:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_post', django.db.models.manager.Manager()),
            ],
        ),
    ]
